# https://taskfile.dev

version: '3'

output: 
  group:
    begin: '::group::{{.TASK}}'
    end: '::endgroup::'
    
tasks:
  fmt:
    desc: "Format with go fmt"
    cmds:
      - go fmt ./...
  lint:  
    desc: "Lint with golangci-lint default settings"
    deps:
      - fmt
    cmds:
      - golangci-lint run
  
  test:
    desc: "Runs test suite"
    cmds:
      - go test ./...
    
  build:
    desc: "Builds the project"
    sources:
      - './**/*.go'
    generates:
      - bin/weather
    cmds:
      - go build -o bin/weather ./cmd/weather
    
  ci:
    desc: "Lint, test, and build the code"
    deps:
      - lint 
      - test
      - build 